---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: shell
  data_path: .
  script: test/fixtures/bootstrap.sh

# verifier:
#   ruby_bindir: <%= ENV['MY_RUBY_HOME'] || '/opt/sensu/embedded' %>/bin
verifier:
  ruby_bindir: /usr/local/bin

platforms:
  - name: debian-8

suites:
  # - name: ruby-210
  #   driver:
  #     image: ruby:2.2-slim
  # - name: ruby-230
  #   driver:
  #     image: ruby:2.3.0-slim
  # - name: ruby-220
  #   driver:
  #     image: ruby:2.2-slim
  - name: default
    driver:
      image: ruby:2.4.1-slim

